from unittest import TestCase


class UtilsTestCase(TestCase):
    def test_country_enum_get_full(self): ...

    def test_validate_amount(self): ...

    def test_validate_interval(self): ...

    def test_add_to_payload(self): ...

    def test_append_query_params(self): ...
