name: Generate [version] documentation

on:
  release:
    types: [ published ]

jobs:
  build:
    name: Deploy docs to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          fetch-depth: 0
      - uses: astral-sh/setup-uv@v1
        with:
          version: "latest"
      - name: Install dependencies
        run: uv sync -p 3.10
      - name: Setup doc deploy
        run: |
          git config --global user.name Docs deploy
          git config --global user.email docs@dummy.bot.com
      - name: Set release notes tag
        run: |
          export RELEASE_TAG_VERSION="${{ github.event.release.tag_name }}"
          echo RELEASE_TAG_VERSION="${RELEASE_TAG_VERSION:1}" >> "$GITHUB_ENV"
      - name: Build docs website
        run: uv run mike deploy "${RELEASE_TAG_VERSION}" --push